### PR TITLE
Added -q option to update to suppress commit logs

### PR DESCRIPTION
**Pull request by hugoh**
voom update always shows the commit log. Added a -q option to hide it.

### CODE REVIEW

**Comment by airblade** [comment]
Thanks for this.

I pulled your changes and ran `voom update`.  Most of my plugins updated by a handful of commits but vim-rails listed 1533 commits and vim-go 2065.  I can't explain that but I don't think it's related to your change.

Anyway, I've had trouble in the past when updating plugins with the output from each getting interleaved, because each plugin updates in the background.  It's hard to reproduce, but I wonder whether introducing two `printf` statements (when `-q` is not given) would open a window in which interleaving could occur.  I think it would be safer to have a single `printf` on each side of the quietness conditional.  Would you mind implementing that?

**Comment by hugoh** [comment]
Oh, I completely forgot about the concurrency of those updates. I'll fix it.

**Comment by hugoh** [comment]
@airblade - see the updated patch

**Comment by airblade** [comment]
Thanks again.

**Pull request merged**
