### PR TITLE
Tilde(~)-expansion for local directories

### PR DESCRIPTION
**Pull request by dezza**

### CODE REVIEW

**Comment by airblade** [comment]
Thanks for this.

Doesn't the shell treat `~` as `$HOME` anyway?

Bash manual: [tilde expansion](https://www.gnu.org/software/bash/manual/html_node/Tilde-Expansion.html).

**Comment by dezza** [comment]
Yes it does :)

But I found out `realpath` is special in this case. It will put `~` in single-quotes, so it can't expand on that! ([More info...](https://stackoverflow.com/a/27485157/169854)

I thought about making a more verbose condition, but it didn't really seem worth it or necessary.

**Comment by airblade** [comment]
Oh, ok.  I can't say I understand it fully.  Bash... ¯\_(ツ)_/¯

I presume the problem you ran into was the vim doesn't load plugins linked to an unexpanded tilde path?  It's a bit surprising to me that it doesn't because I can `cd` through the link.

**Comment by airblade** [comment]
Anyway, thanks for the fix!

**Comment by dezza** [comment]
Correct yes it wouldn't, I was puzzled by the single quotes, but it makes sense after reading. If you typed it in interactively it would expand.

I think this solution is better than the long answers or a verbose conditional with extra steps.

I love voom btw, I can take a look in the future and see if I can clean it up.

**Pull request merged**
